### ISSUE TITLE
Default options

### ISSUE THREAD

**Issue by fredrkr** [kamaln7/toastr#6]
I published the config-file and added a couple of options so that it looks like this:

```php
return array(
    'options' => array(
    	'closeButton' => true,
    	'progressBar' => true
    )
);
```

I'm expecting these to be the default options, as your docs say, but they are only applied if I include a non-empty array to the toastr-calls. Consider the following.

```php
// Default options are NOT applied
Toastr::error('Text', 'Title');
Toastr::error('Text', 'Title', array());
Toastr::error('Text', 'Title', []);

// Default options ARE applied
Toastr::error('Text', 'Title', array('foo' => 'bar'));
Toastr::error('Text', 'Title', [null]);
```

Wouldn't it make more sense if I could just call Toastr::error('Text', 'Title'), and the default options would be applied?

**Comment by kamaln7** [comment]
Thanks! I totally missed that. :+1:
